# Funding links
# Uncomment and fill in the platforms you want to use

# github: username
# patreon: username
# ko_fi: username
# buy_me_a_coffee: username
# liberapay: username
# custom: ["https://example.com/donate"]
