# yamllint configuration
# https://yamllint.readthedocs.io/

extends: default

rules:
  # Allow long lines (common in Docker Compose)
  line-length:
    max: 200
    level: warning

  # Allow document start without ---
  document-start: disable

  # Allow comments without space after #
  comments:
    require-starting-space: false
    min-spaces-from-content: 1

  # Indentation settings
  indentation:
    spaces: 2
    indent-sequences: true

  # Truthy values (yes/no, on/off)
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

ignore: |
  .github/
  node_modules/
  vendor/
